### ISSUE TITLE
[HELP] Error when using Mode.DOM

### ISSUE THREAD

**Issue by Shabinder** [skrapeit/skrape.it#100]
**Describe the bug**
following Error when using Mode.DOM

**Expected behavior**
Should scrap data .

**Error**
Exception in thread "main" java.lang.NoSuchFieldError: BEST_SUPPORTED
	at it.skrape.core.fetcher.BrowserFetcher.fetch(BrowserFetcher.kt:18)
	at it.skrape.core.Scraper.scrape(Scraper.kt:12)
	at com.shabinder.spotiflyer.testing.Html_scrapingKt$main$extracted$1.invoke(html scraping.kt:58)
	at com.shabinder.spotiflyer.testing.Html_scrapingKt$main$extracted$1.invoke(html scraping.kt)
	at it.skrape.DslKt.skrape(Dsl.kt:16)
	at com.shabinder.spotiflyer.testing.Html_scrapingKt.main(html scraping.kt:33)
	at com.shabinder.spotiflyer.testing.Html_scrapingKt.main(html scraping.kt)

Process finished with exit code 1

**Comment by Shabinder** [comment]
Now This After updating dependency to     implementation 'net.sourceforge.htmlunit:htmlunit:2.37.0'


Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.configureHttpsScheme(HttpWebConnection.java:636)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.createHttpClientBuilder(HttpWebConnection.java:559)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.getHttpClientBuilder(HttpWebConnection.java:520)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:172)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1436)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1355)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:415)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:336)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:488)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:469)
	at it.skrape.core.fetcher.BrowserFetcher.fetch(BrowserFetcher.kt:20)
	at it.skrape.core.Scraper.scrape(Scraper.kt:12)
	at com.shabinder.spotiflyer.testing.Html_scrapingKt$main$extracted$1.invoke(html scraping.kt:58)
	at com.shabinder.spotiflyer.testing.Html_scrapingKt$main$extracted$1.invoke(html scraping.kt)
	at it.skrape.DslKt.skrape(Dsl.kt:16)
	at com.shabinder.spotiflyer.testing.Html_scrapingKt.main(html scraping.kt:33)
	at com.shabinder.spotiflyer.testing.Html_scrapingKt.main(html scraping.kt)

Process finished with exit code 1

**Comment by christian-draeger** [comment]
hey which version and which buildtool are you using?
usually you should not need to manage transitiv dependencies manually. gradle or maven should do the job automatically for you.

**Comment by Shabinder** [comment]
It seemed to be an issue in Android Gradle build ...
It's seems to be a different Apache http clients which android comes with doesn't have Instance ,
The same error come while using HTML unit in Android too.

**Comment by christian-draeger** [comment]
since this seems to be an issue with html unit i will close this issue for now
