### ISSUE TITLE
[HELP] Importing this library causes a build error

### ISSUE THREAD

**Issue by fatalade** [skrapeit/skrape.it#103]
For some reason, as soon as I import this library and do a gradle sync, my build fails. This is the error I get,

```
java.util.concurrent.ExecutionException: com.android.tools.r8.errors.a: Space characters in SimpleName 'to be' are not allowed prior to DEX version 040
		at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)
		at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:513)
		at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:86)
		at com.android.tools.r8.utils.U0.a(:14)
		at com.android.tools.r8.dex.a.a(:68)
```

Any help would be appreciated. Cheers.

**Comment by fatalade** [comment]
Looks like it's caused when desugaring is used (https://developer.android.com/studio/write/java8-support). Y'all can close this issue.
