### ISSUE TITLE
[BUG] org.fusesource.jansi.WindowsAnsiOutputStream

### ISSUE THREAD

**Issue by Exobitt** [skrapeit/skrape.it#167]
When trying to built a project with gradle on windows, i keep getting a ClassNotFoundException, caused by org.fusesource.jansi.WindowsAnsiOutputStream.

`
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.WindowsAnsiOutputStream
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.WindowsAnsiOutputStream

	at 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
	at 	... 65 common frames omitted
`

**Comment by christian-draeger** [comment]
version 1.1.6 including the jansi fix has just been released to maven central. have fun :)
