### ISSUE TITLE
I am getting this error on android 

### ISSUE THREAD

**Issue by sampatsharma143** [skrapeit/skrape.it#234]
my app is crashing and giving me this error : 
Process: com.shunyank.pricedekho, PID: 19009
java.lang.NoClassDefFoundError: Failed resolution of: Lio/ktor/client/features/HttpTimeout;
Caused by: java.lang.ClassNotFoundException: Didn't find class "io.ktor.client.features.HttpTimeout" on path: DexPathList[[dex file "/data/data/com.shunyank.pricedekho/code_cache/.overlay/base.apk/classes3.dex", dex file "/data/data/com.shunyank.pricedekho/code_cache/.overlay/base.apk/classes11.dex", zip file "/data/app/~~STSNY8oMm_QOSAJAmH66VA==/com.shunyank.pricedekho-RA41bh6pTyq3315b_k1JXw==/base.apk"],nativeLibraryDirectories=[/data/app/~~STSNY8oMm_QOSAJAmH66VA==/com.shunyank.pricedekho-RA41bh6pTyq3315b_k1JXw==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
please help me fix this issue

**Comment by sampatsharma143** [comment]
i fixed this issue by updating the library to     implementation("it.skrape:skrapeit:1.3.0-alpha.1")
