### ISSUE TITLE
[QUESTION] Getting Error even while wunning Example Program

### ISSUE THREAD

**Issue by Shabinder** [skrapeit/skrape.it#99]
**describe what you want to archive**
configure Skrape{it}, as its throwing error!

**Code Sample**
fun main() {
    val links: List<String> = skrape {
        url = "https://kotlinlang.org/docs/reference/"
        mode = Mode.SOURCE
        extract {
            htmlDocument {
                a {
                    findAll {
                        eachHrefAsAbsoluteLink
                    }
                }
            }
        }
    }
    println(links)
}
**Error**
Exception in thread "main" java.lang.NoClassDefFoundError: io/github/rybalkinsd/kohttp/client/DefaultHttpClientKt
	at it.skrape.core.fetcher.HttpFetcher.configuredClient(HttpFetcher.kt:34)
	at it.skrape.core.fetcher.HttpFetcher.fetch(HttpFetcher.kt:21)
	at it.skrape.core.Scraper.scrape(Scraper.kt:13)
	at it.skrape.DslKt.extract(Dsl.kt:32)
	at com.shabinder.spotiflyer.testing.Html_scrapingKt$main$links$1.invoke(html scraping.kt:14)
	at com.shabinder.spotiflyer.testing.Html_scrapingKt$main$links$1.invoke(html scraping.kt)
	at it.skrape.DslKt.skrape(Dsl.kt:16)
	at com.shabinder.spotiflyer.testing.Html_scrapingKt.main(html scraping.kt:11)
	at com.shabinder.spotiflyer.testing.Html_scrapingKt.main(html scraping.kt)
Caused by: java.lang.ClassNotFoundException: io.github.rybalkinsd.kohttp.client.DefaultHttpClientKt
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 9 more

Process finished with exit code 1

**Comment by Shabinder** [comment]
implementation 'io.github.rybalkinsd:kohttp:0.12.0'
Oops,missed this!
